# Generated by Django 5.0.6 on 2024-06-30 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='address',
        ),
        migrations.AlterField(
            model_name='criminal',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='criminal',
            name='criminal_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criminal.criminalclass'),
            preserve_default=False,
        ),
    ]
