# Generated by Django 5.0.6 on 2024-07-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_criminalclass_remove_criminal_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CriminalClass',
            new_name='Class',
        ),
    ]
