# Generated by Django 5.0.6 on 2024-07-01 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0003_rename_criminalclass_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Classification',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='criminal_classification',
            new_name='criminal_classification_id',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='description',
        ),
        migrations.AddField(
            model_name='criminal',
            name='crime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criminal',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='criminal',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='criminal',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('criminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal.criminal')),
            ],
        ),
    ]
